include:   
  - project: 'gitlab-samples/templates'
    ref: main
    file: '/maven-workflow.yaml'

stages:
  - build
  - inspect
  - test
  - scan
  - publish
  - buildImage
  - scanImage
  - publishImage
  - devDeploy
  - testDeploy
  - verify
  - prodDeploy

#Include any custom jobs
#myCustomJob:
#  stage: custom
#  script: echo "custom job"

