apiVersion: apps/v1
kind: Deployment
metadata:
  name: cigithubaction
  labels:
    app: cigithubaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cigithubaction
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate      
  template:
    metadata:
      labels:
        app: cigithubaction
    spec:
      containers:
      - name: cigithubaction
        image: judebantony.jfrog.io/default-docker-local/cigithubaction:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 18080
